# Generated by Django 5.1.6 on 2025-02-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standaard', 'Standaard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('familiekamer', 'Familiekamer')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
