# Generated by Django 5.1.6 on 2025-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
