# Generated by Django 5.1.6 on 2025-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_room_image_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Nog geen beschrijving beschikbaar.'),
        ),
    ]
