# Generated by Django 5.1.6 on 2025-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
